version : "3.8"

services :
  mysqldb :
    image : mysql:5.7
    restart : unless-stopped
    ports :
      - 3307:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes :
      - db:/var/lib/mysql
  kaddem-backend :
    depends_on:
      - mysqldb
    build : ./
    restart : on-failure
    ports :
      - 8089:8089
    volumes :
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes :
  db :
