version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  gestion-station-ski:
    depends_on:
      - mysqldb
    image: amiraaissaoui91/projetkaddem
    restart: on-failure
    build: ./
    ports:
      - "8089:8089"
    volumes: 
      - .m2:/root/.m2
    stdin_open: true
    tty: true


volumes:
  db: