version: '3.3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:  
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'     
      MYSQL_DATABASE: kaddem
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    networks:
      - app-network

  backend-container:
    image: yassinebarkallah/back:latest 
    container_name: backend-container
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/kaddem
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:
  mysql_config:
networks:
  app-network:
    driver: bridge
